version: '3.8'

services:
  table-extractor-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: table-extractor-api
    ports:
      - "5006:5000"
    volumes:
      - ./uploads:/app/uploads
      - ./outputs:/app/outputs
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1 